DEVICE_PATH := device/Haier/B85-D

USE_CAMERA_STUB := true

TARGET_ARCH := arm
TARGET_BOARD_PLATFORM := MT6589
TARGET_CPU_ABI := armeabi-v7a
TARGET_CPU_ABI2 := armeabi
TARGET_ARCH_VARIANT := armv7-a-neon
TARGET_CPU_VARIANT := cortex-a7
TARGET_CPU_SMP := true
ARCH_ARM_HAVE_TLS_REGISTER := true

# blob hacks
COMMON_GLOBAL_CFLAGS += -DMR1_AUDIO_BLOB -DDISABLE_HW_ID_MATCH_CHECK -DNEEDS_VECTORIMPL_SYMBOLS -DMTK_SERIALNO_FIX
BOARD_HAVE_PRE_KITKAT_AUDIO_BLOB := true
BOARD_HAVE_PRE_KITKAT_AUDIO_POLICY_BLOB := true
TARGET_RUNNING_WITHOUT_SYNC_FRAMEWORK := true

# HW Composer
BOARD_NEEDS_OLD_HWC_API := true
COMMON_GLOBAL_CFLAGS += -DMTK_G_MT6589
COMMON_GLOBAL_CPPFLAGS += -DMTK_G_MT6589

# power
TARGET_POWERHAL_VARIANT := cm

# boot
TARGET_NO_BOOTLOADER := false

# EGL settings
BOARD_EGL_CFG := device/Haier/B85-D/egl.cfg
USE_OPENGL_RENDERER := true
BOARD_EGL_WORKAROUND_BUG_10194508 := true

# kernel
TARGET_PREBUILT_KERNEL := $(DEVICE_PATH)/kernel
BOARD_KERNEL_CMDLINE :=
BOARD_KERNEL_BASE := 0x10000000
BOARD_KERNEL_PAGESIZE := 2048
LZMA_RAMDISK_TARGETS := recovery

# fix this up by examining /proc/mtd on a running device
BOARD_BOOTIMAGE_PARTITION_SIZE := 0x0600000
BOARD_RECOVERYIMAGE_PARTITION_SIZE := 0x0600000
BOARD_SYSTEMIMAGE_PARTITION_SIZE := 0x38000000
BOARD_USERDATAIMAGE_PARTITION_SIZE := 0x9B700000
BOARD_FLASH_BLOCK_SIZE := 512
TARGET_USERIMAGES_USE_EXT4 := true
TARGET_USERIMAGES_USE_F2FS := true

BOARD_HAS_NO_SELECT_BUTTON := true
BOARD_HAS_LARGE_FILESYSTEM := true

TARGET_RECOVERY_FORCE_PIXEL_FORMAT := RGB_565
DEVICE_RESOLUTION := 1024x768
TARGET_RECOVERY_DENSITY := hdpi
TW_THEME := portrait_hdpi

# mkimage to append headers
TARGET_MKIMAGE := $(DEVICE_PATH)/mkimage
TARGET_USE_BUILT_BOOTIMAGE := true

TW_INTERNAL_STORAGE_PATH := "/emmc"
TW_INTERNAL_STORAGE_MOUNT_POINT := "emmc"
TW_EXTERNAL_STORAGE_PATH := "/sdcard"
TW_EXTERNAL_STORAGE_MOUNT_POINT := "sdcard"

TW_DEFAULT_EXTERNAL_STORAGE := true
TW_FLASH_FROM_STORAGE := true
RECOVERY_GRAPHICS_USE_LINELENGTH := true
TW_NO_REBOOT_BOOTLOADER := false
TARGET_RECOVERY_FSTAB := $(DEVICE_PATH)/recovery/etc/twrp.fstab
TW_USE_BRAND_DEVICE_HARDWARE_ID_FOR_DEVICE_ID := true
TW_BRIGHTNESS_PATH := /sys/devices/platform/leds-mt65xx/leds/lcd-backlight/brightness
TW_MAX_BRIGHTNESS := 255
TW_CUSTOM_BATTERY_PATH := /sys/devices/platform/battery/power_supply/battery
TW_BACKUPS_FOLDER := /sdcard/TWRP/BACKUPS/Haier_B85-D_MT6589

TW_EXCLUDE_SUPERSU := true
#TW_NO_EXFAT := true
#TW_NO_EXFAT_FUSE := true
#BOARD_HAS_NO_REAL_SDCARD := true

BOARD_CUSTOM_BOOTIMG_MK := $(DEVICE_PATH)/boot.mk
#TWHAVE_SELINUX := true
TW_INCLUDE_NTFS_3G := true
